apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "owasp-nest.fullname" . }}-backend
  labels:
    {{- include "owasp-nest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "owasp-nest.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "owasp-nest.selectorLabels" . | nindent 8 }}
        component: backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.backend.image.securityContext | nindent 12 }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "owasp-nest.fullname" . }}-backend-config
            - secretRef:
                name: {{ include "owasp-nest.fullname" . }}-backend-secrets
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5