apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}