apiVersion: v2
name: owasp-nest
description: OWASP Nest Application
version: 1.0.0
appVersion: "2.0.0"
dependencies:
- name: postgresql
  version: 13.2.8
  repository: https://charts.bitnami.com/bitnami
- name: victoria-metrics-single
  version: ~0.8.0
  repository: https://victoriametrics.github.io/helm-charts/
  condition: victoria-metrics-single.enabled
- name: grafana
  version: ~6.50.0
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled