global:
  env: production
  domain: nest.owasp.org

backend:
  replicaCount: 3
  image:
    tag: production
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi

frontend:
  replicaCount: 3
  image:
    tag: production
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi

postgresql:
  persistence:
    size: 50Gi
    storageClass: "gp2"

prometheus:
  enabled: true
  alertmanager:
    config:
      global:
        slack_api_url: $SLACK_WEBHOOK

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: nest-prod-tls
      hosts:
        - nest.owasp.org