global:
  appName: "owasp-nest"
  environment: "local"
  domain: "nest.local"
  clusterDomain: "cluster.local"

backend:
  replicaCount: 2
  image:
    repository: arkid15r/owasp-nest-backend
    tag: latest
    pullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  service:
    type: ClusterIP
    port: 8000

frontend:
  replicaCount: 2
  image:
    repository: arkid15r/owasp-nest-frontend
    tag: latest
    pullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  service:
    type: ClusterIP
    port: 3000

postgresql:
  enabled: true
  architecture: "replication"
  auth:
    database: "nest_db"
    username: "nest_user"
    existingSecret: "nest-db-secret"
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "gp2"
  primary:
    podSecurityContext:
      fsGroup: 1001
    containerSecurityContext:
      runAsNonRoot: true
      runAsUser: 1001

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: "nest.local"
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend
              port:
                number: 8000
  tls:
    - secretName: "nest-tls"
      hosts:
        - "nest.local"

vault:
  enabled: false
  address: "https://vault.example.com"
  role: "nest-app"

monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true

victoria-metrics-single:
  podSecurityPolicy:
    enabled: false  # Disable deprecated PSP
  securityContext:
    enabled: true   # Enable modern PSA
    fsGroup: 1001
    runAsUser: 1001