global:
  env: development
  domain: nest.local
  
backend:
  replicaCount: 2
  image:
    repository: arkid15r/owasp-nest-backend
    tag: latest
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
  env:
    config:
      DJANGO_ALGOLIA_APPLICATION_REGION: None
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_CONFIGURATION: Test
      DJANGO_OPEN_AI_SECRET_KEY: None
      DJANGO_PUBLIC_IP_ADDRESS: "127.0.0.1"
      DJANGO_RELEASE_VERSION: None
    secret:
      DJANGO_ALGOLIA_APPLICATION_ID: None
      DJANGO_ALGOLIA_EXCLUDED_LOCAL_INDEX_NAMES: None
      DJANGO_ALGOLIA_WRITE_API_KEY: None
      DJANGO_AWS_ACCESS_KEY_ID: None
      DJANGO_AWS_SECRET_ACCESS_KEY: None
      DJANGO_DB_HOST: None
      DJANGO_DB_NAME: None
      DJANGO_DB_PORT: None
      DJANGO_DB_PASSWORD: None
      DJANGO_DB_USER: None
      DJANGO_SECRET_KEY: None
      DJANGO_SENTRY_DSN: None
      DJANGO_SLACK_BOT_TOKEN: None
      DJANGO_SLACK_SIGNING_SECRET: None
      GITHUB_TOKEN: None

frontend:
  replicaCount: 2
  image:
    repository: arkid15r/owasp-nest-frontend
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    config:
      VITE_API_URL: http://localhost:8000/api/v1/
      VITE_ENVIRONMENT: local
      VITE_GRAPHQL_URL: http://localhost:8000/graphql/
      VITE_GTM_AUTH: your-google-tag-manager-auth
      VITE_GTM_ID: your-google-tag-manager-id
      VITE_GTM_PREVIEW: None
      VITE_IDX_URL: http://localhost:8000/idx/
      VITE_RELEASE_VERSION: 
      VITE_SENTRY_DSN: None

postgresql:
  enabled: true
  auth:
    database: nest
    username: nest
    password: "changeme"
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: nest.local
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix
  tls:
    - secretName: nest-tls
      hosts:
        - nest.local

prometheus:
  enabled: true
  alertmanager:
    config:
      global:
        slack_api_url: ""
      route:
        receiver: 'slack'
      receivers:
      - name: 'slack'
        slack_configs:
        - channel: '#alerts'
          send_resolved: true

grafana:
  enabled: true
  adminPassword: "securepassword"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: VictoriaMetrics
          type: prometheus
          url: http://victoria-metrics-single-server:8428
          access: proxy
  dashboards:
    default:
      victoriametrics:
        gnetId: 10229  # Sample VictoriaMetrics dashboard ID
        revision: 1
        datasource: VictoriaMetrics
