global:
  env: development
  domain: nest.local
  
backend:
  replicaCount: 2
  image:
    repository: arkid15r/owasp-nest-backend
    tag: latest
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
  env:
    config:
      DJANGO_SETTINGS_MODULE: settings.production
      DJANGO_DEBUG: "False"
  
frontend:
  replicaCount: 2
  image:
    repository: arkid15r/owasp-nest-frontend
    tag: latest
  resources:
    limits:
      cpu: 500m
      memory: 512Mi

postgresql:
  enabled: true
  auth:
    database: nest
    username: nest
    password: "changeme"
  persistence:
    enabled: true
    size: 10Gi
    storageClass: "standard"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: nest.local
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix
  tls:
    - secretName: nest-tls
      hosts:
        - nest.local

prometheus:
  enabled: true
  alertmanager:
    config:
      global:
        slack_api_url: ""
      route:
        receiver: 'slack'
      receivers:
      - name: 'slack'
        slack_configs:
        - channel: '#alerts'
          send_resolved: true

grafana:
  enabled: true
  adminPassword: "securepassword"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: VictoriaMetrics
          type: prometheus
          url: http://victoria-metrics-single-server:8428
          access: proxy
  dashboards:
    default:
      victoriametrics:
        gnetId: 10229  # Sample VictoriaMetrics dashboard ID
        revision: 1
        datasource: VictoriaMetrics
